name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the CI environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the project
      run: |
        npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch that will be used for GitHub Pages
        folder: build     # The folder to deploy (this should be the build folder for React apps)
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

